PSS/MZXRM.PSS.WebClient/Models/Seiving.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MZXRM.PSS.WebClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seiving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seiving()
        {
            this.SeivingSizeQties = new HashSet<SeivingSizeQty>();
        }
    
        public int ID { get; set; }
        public string SeivingNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StoreId { get; set; }
        public Nullable<int> VesselId { get; set; }
        public string FromSize { get; set; }
        public Nullable<decimal> FromQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Origin { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeivingSizeQty> SeivingSizeQties { get; set; }
    }
}

PSS/MZXRM.PSS.WebClient/Controllers/StoreController.cs
using MZXRM.PSS.Business;
using MZXRM.PSS.Common;
using MZXRM.PSS.Data;
using MZXRM.PSS.WebClient.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MZXRM.PSS.WebClient.Models;

namespace PatrocoalSalesSystem.Controllers
{
    public class StoreController : Controller
    {
        PetrocoalEntities db = new PetrocoalEntities();
        // GET: Store
        public ActionResult Index()
        {
            try
            {
                Common.MyUrl = Request.RawUrl;
                if (!Common.isAuthorize())
                    Response.Redirect("/Login");
                List<Store> allStores = StoreManager.AllStore;

                ViewBag.Stores = allStores;

            }
            catch (Exception ex)
            {
                ExceptionHandler.Error("Error! " + ex.Message, ex);
            }
            return View();
        }
        public FileResult Download(string id)
        {
            try
            {
                Store thisStore = StoreManager.GetStore(new Guid(id));

                //Get result file stream
                MemoryStream fileForDownload = ExcelUtil.GenerateStoreReport(thisStore);
                return File(fileForDownload.ToArray(), "application/vnd.ms-excel", thisStore.Name + ".xls");
            }
            catch (Exception ex)
            {
                ExceptionHandler.Error("Error! " + ex.Message, ex);
            }
            return null;
        }
        public ActionResult StoreInOut()
        {
          
            try
            {
                Common.MyUrl = Request.RawUrl;
                if (!Common.isAuthorize())
                    Response.Redirect("/Login");
                List<StoreTransfer> allStoreIO = StoreManager.AllStoreInOut;

                ViewBag.StoresInOuts = allStoreIO;

            }
            catch (Exception ex)
            {
                ExceptionHandler.Error("Error! " + ex.Message, ex);
            }
            return View();
        }
        public ActionResult Seiving()
        {
            MZXRM.PSS.WebClient.Models.Seiving seiving = new MZXRM.PSS.WebClient.Models.Seiving();
            ViewBag.ThisCust = !string.IsNullOrEmpty(Request.QueryString["cust"]) ? CustomerManager.GetCustomer(Guid.Parse(Request.QueryString["cust"])) : null;


            return View(seiving);
            //return View();
        }

        [HttpPost]
        public ActionResult Seiving(MZXRM.PSS.WebClient.Models.Seiving seiving, FormCollection fomr)
        {
            List<MZXRM.PSS.WebClient.Models.SeivingSizeQty> seivingSizeQtyList = new List<MZXRM.PSS.WebClient.Models.SeivingSizeQty>();
            var size = Common.Size;
            foreach (var m in size)
            {
                string value = Request.Form["Qty_" + m.Index.ToString()];

                if (value != null)
                {
                    decimal qty = decimal.Parse(value);

                    MZXRM.PSS.WebClient.Models.SeivingSizeQty seivingSizeQty = new MZXRM.PSS.WebClient.Models.SeivingSizeQty();

                    seivingSizeQty.SizeId = m.Index;
                    seivingSizeQty.SizeQuantity = qty;
                    seivingSizeQtyList.Add(seivingSizeQty);
                }
            }
            seiving.SeivingSizeQties = seivingSizeQtyList;
            seiving.SeivingNo = GenerateSeivingNumber();

            if (ModelState.IsValid)
            {
                db.Seivings.Add(seiving);
                db.SaveChanges();

            }
            return View(seiving);
        }

        public ActionResult SizeList()
        {
            List<Size> sizeList = new List<Size>();

            //Size size1 = new Size()
            //{ID=1,
            //Name = "Test1"

            //};

            //size.Add(size1);
            var size = Common.Size;

            foreach (var item in size)
            {
                Size size1 = new Size()
                {
                    Id = item.Index,
                    Name = item.Value
                };
                sizeList.Add(size1);

            }

            return PartialView("SizeListing", sizeList);
        }
        public ActionResult SeivingCreate()
        {
            MZXRM.PSS.WebClient.Models.Seiving seiving = new MZXRM.PSS.WebClient.Models.Seiving();


            return View(seiving);
        }
        [HttpPost]
        public ActionResult SeivingCreate(MZXRM.PSS.WebClient.Models.Seiving seiving, FormCollection fomr)
        {
            List<MZXRM.PSS.WebClient.Models.SeivingSizeQty> seivingSizeQtyList = new List<MZXRM.PSS.WebClient.Models.SeivingSizeQty>();
            var size = Common.Size;
            foreach (var m in size)
            {
                string value = Request.Form["Qty_" + m.Index.ToString()];

                if (value != null)
                {
                    decimal qty = decimal.Parse(value);

                    MZXRM.PSS.WebClient.Models.SeivingSizeQty seivingSizeQty = new MZXRM.PSS.WebClient.Models.SeivingSizeQty();

                    seivingSizeQty.SizeId = m.Index;
                    seivingSizeQty.SizeQuantity = qty;
                    seivingSizeQtyList.Add(seivingSizeQty);
                }
            }
            seiving.SeivingSizeQties = seivingSizeQtyList;
            

            if (ModelState.IsValid)
            {
                db.Seivings.Add(seiving);
                db.SaveChanges();

            }
            return View(seiving);
        }


        public ActionResult SeivingList()
        {
            var sevingList = (from m in db.Seivings
                              select m).ToList();

            foreach (var j in sevingList) {

                var svQtyListByID = (from n in db.SeivingSizeQties
                         where n.SeivingID == j.ID
                         select n).ToList();

                j.SeivingSizeQties = svQtyListByID;
                        }
            return PartialView("SeivingList", sevingList);
        }

        private string GenerateSeivingNumber()
        {
            var seivings = (from s in db.Seivings
                            select s).ToList();

            int lNumber = 1001;
            foreach (var svn in seivings)
            {
                string svNumber = svn.SeivingNo.Replace("SV-", "");
                int No = int.Parse(svNumber);
                if (No > lNumber)
                    lNumber = No;
            }
            lNumber++;
            return "SV-" + lNumber.ToString();
        }

        #region /Purchase/CreateGRN
        public ActionResult CreateStoreTransfer()
        {
            Common.MyUrl = Request.RawUrl;
            if (!Common.isAuthorize())
                Response.Redirect("/Login");
            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult CreateStoreTransfer(FormCollection form)
        {
            try
            {
                if (!Common.isAuthorize())
                {
                    ExceptionHandler.Error("Session Timeout");
                    return View();
                }
                if (form["btn"] != null && form["btn"] == "Reset")
                    return View();

                Dictionary<string, string> values = new Dictionary<string, string>();
                foreach (string Key in form.Keys)
                {
                    values.Add(Key, form[Key]);
                }
                string formErrors = StoreManager.ValidateCreateStoreTransferForm(values);
                if (formErrors == "")
                {
                    StoreTransfer storeio = StoreManager.CreateStoreTransfer(values);
                    Response.Redirect("/Store/StoreInOut");
                }
                else
                    ExceptionHandler.Warning("Validation! " + formErrors);
            }
            catch (Exception ex)
            {
                ExceptionHandler.Error("Error! " + ex.Message, ex);
            }
            return View(form);
        }
        #endregion

        public ActionResult StoreDetail(string id)
        {
            try
            {
                Common.MyUrl = Request.RawUrl;
                if (!Common.isAuthorize())
                    Response.Redirect("/Login");
                if (string.IsNullOrEmpty(id))
                    ExceptionHandler.Error("Error! No Store Found");
                Guid StoreId = Guid.Empty;
                if (Guid.TryParse(id, out StoreId))
                {
                    Store ThisStore = StoreManager.GetStore(StoreId);
                    ViewBag.ThisStore = ThisStore;
                }
            }
            catch (Exception ex)
            {
                ExceptionHandler.Error("Error! " + ex.Message, ex);
            }
            return View();
        }
        #region /store/updatestoretransfer
        public ActionResult UpdateStoreTransfer(string id)
        {
            Common.MyUrl = Request.RawUrl;
            if (!Common.isAuthorize())
                return Redirect("/Login");
            if (string.IsNullOrEmpty(id))
                return Redirect("/Purchase");
            StoreTransfer ThisST = StoreManager.GetStoreTransfer(id);
            if (ThisST == null)
                return Redirect("/Store");
            ViewBag.ThisST = ThisST;
            return View();
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult UpdateStoreTransfer(FormCollection form)
        {
            if (!Common.isAuthorize())
            {
                ExceptionHandler.Error("Session Timeout");
                return View();
            }

PSS/MZXRM.PSS.WebClient/Views/Store/CreateStoreTransfer.cshtml
@using MZXRM.PSS.Data
@using MZXRM.PSS.Business
@using MZXRM.PSS.Common

<section class="content-header">
    <h1>
        Store In/Out
        <small>Store to Store stock movement</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="/stock"><i class="fa fa-dashboard"></i> Stock</a></li>
        <li class="active">Store In/Out</li>
    </ol>
</section>

<!-- Main content -->
<section class="content container-fluid">
    <form method="post" action="/Store/CreateStoreTransfer">
        @if (ExceptionHandler.HasException())
        {
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                @ExceptionHandler.GetExceptionMessage()
            </div>
            { ExceptionHandler.CloseException(); }
        }
        <div class="box box-default box-solid">
            <!-- /.box-header -->
            <div class="box-body">
                <div class="col-lg-6">
                    <button type="submit" class="btn btn-sm btn-primary" name="btn" value="Save"><i class="fa fa-floppy-o"></i> Save</button>
                    <button type="reset" class="btn btn-sm btn-default" name="btn" value="Reset"><i class="fa fa-refresh"></i> Reset</button>
                </div>
                <div class="col-lg-6">
                    <a href="/Store/StoreInOut" class="btn btn-sm btn-default"><i class="fa fa-list"></i> All Store In/Outs</a>
                    <a href="/Store" class="btn btn-sm btn-default"><i class="fa fa-list"></i> All Store</a>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <div class="box box-warning box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">New Store Transfer</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>From Store</label>
                            <select class="form-control select2" name="FromStore">
                                <option value="0">--- From Store ---</option>
                                @foreach (Store store in StoreManager.AllStore)
                                {
                                    <option value="@store.Id"  @(store.Id.ToString() == Request.Form["FromStore"] ? " selected " : "")>@store.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Date:</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="form-control pull-right" data-selector="date" name="date" value="@DateTime.Now.ToShortDateString()">
                            </div>
                            <!-- /.input group -->
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>Customer</label>
                            <select class="form-control select2" name="Customer">
                                <option value="0">--- Customer ---</option>
                                @foreach (Customer customer in CustomerManager.AllCustomers)
                                {
                                    <option value="@customer.Id"  @(customer.Id.ToString() == Request.Form["Customer"] ? " selected " : "")>@customer.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label>Origin</label>
                            <select class="form-control" name="Origin">
                                <option value="0">--- Origin ---</option>
                                @foreach (Item Origin in Common.Origin)
                                {
                                    <option value="@Origin.Index"  @(Origin.Index.ToString() == Request.Form["Origin"] ? " selected " : "")>@Origin.Value</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label>Vessel</label>
                            <select class="form-control" name="Vessel">
                                <option value="0">--- Vessel ---</option>
                                @foreach (Item Vessel in Common.Vessel)
                                {
                                    <option value="@Vessel.Index"  @(Vessel.Index.ToString() == Request.Form["Vessel"] ? " selected " : "")>@Vessel.Value</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label>Size</label>
                            <select class="form-control" name="Size">
                                <option value="0">--- Size ---</option>
                                @foreach (Item Size in Common.Size)
                                {
                                    <option value="@Size.Index"  @(Size.Index.ToString() == Request.Form["Size"] ? " selected " : "")>@Size.Value</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Quantity</label>
                            <input type="text" class="form-control" name="Quantity" value="@Request.Form["Quantity"]" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>To Store</label>
                            <select class="form-control select2" name="ToStore">
                                <option value="0">--- To Store ---</option>
                                @foreach (Store store in StoreManager.AllStore)
                                {
                                    <option value="@store.Id" @(store.Id.ToString() == Request.Form["ToStore"] ? " selected " : "")>@store.Name</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Vehicle No</label>
                            <input type="text" class="form-control" name="VehicleNo" value="@Request.Form["VehicleNo"]" />
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Bilty No</label>
                            <input type="text" class="form-control" name="BiltyNo"  value="@Request.Form["BiltyNo"]" />
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Bilty Date:</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="form-control pull-right" data-selector="date" name="BiltyDate" value="@DateTime.Now.ToShortDateString()">
                            </div>
                            <!-- /.input group -->
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Invoice</label>
                            <input type="text" class="form-control" name="Invoice" value="@Request.Form["Invoice"]" />
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Train Number</label>
                            <input type="text" class="form-control" name="CCMNo" value="@Request.Form["CCMNo"]" />
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label>Transporter</label>
                            <select class="form-control" name="Transporter">
                                <option value="0">--- Transporter ---</option>
                                @foreach (Item transporter in Common.Transporter)
                                {
                                    <option value="@transporter.Index" @(transporter.Index.ToString() == Request.Form["Transporter"] ? " selected " : "")>@transporter.Value</option>
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Remarks</label>
                            <input type="text" class="form-control" name="Remarks" value="@Request.Form["Remarks"]" >
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
            </div>
        </div>
    </form>
    <!-- /.box -->

</section>



@section scripts
{
    <script>

        $('input[data-selector=date]').datepicker({
            autoclose: true
        });
    </script>
}


PSS/MZXRM.PSS.WebClient/Views/Store/SeivingCreate.cshtml
@model MZXRM.PSS.WebClient.Models.Seiving

@{
    ViewBag.Title = "SeivingCreate";
}
<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<section class="content-header">
    <h1>
        Seiving
        <small>Seiving Coal</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/home"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Seiving</li>
    </ol>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <div class="box box-default box-solid collapsed-box">
        <div class="box-header with-border">
            <h3 class="box-title">Quick Links</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse">
                    <i class="fa fa-plus"></i>
                </button>
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="col-md-6">
                <div class="col-sm-4">
                    <a href="/stock" class="btn btn-block btn-primary margin">Stock Status</a>
                </div>
                <div class="col-sm-4">
                    <a href="/seiving" class="btn btn-block btn-primary margin">Sieving</a>
                </div>
                <div class="col-sm-4">
                    <a href="/stock" class="btn btn-block btn-primary margin">Wastage</a>
                </div>
                <div class="col-sm-4">
                    <a href="/stock" class="btn btn-block btn-primary margin">Vessel Transfer</a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="col-sm-4">
                    <a href="/Stock" class="btn btn-block btn-info margin ">Stock Status Report</a>
                </div>
                <div class="col-sm-4">
                    <a href="/Purchase" class="btn btn-block btn-info margin ">TODO</a>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

    @using (Html.BeginForm("SeivingCreate", "Store", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="box box-warning box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Create Seiving</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.SeivingNo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SeivingNo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SeivingNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StoreId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StoreId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StoreId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VesselId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VesselId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VesselId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CoalDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CoalDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CoalDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FromSize, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FromSize, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FromSize, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FromQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FromQuantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FromQuantity, "", new { @class = "text-danger" })
                </div>
            </div>




            <div id="model-listing">

            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Remarks, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>

    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</section>
<script type="text/javascript">

    $(document).ready(function () {
            $.ajax({
                url: '@Url.Content("SizeList")'
            })
                .done(function (partialViewResult) {
                    $("#model-listing").html(partialViewResult);
                });
        });
</script>

PSS/MZXRM.PSS.WebClient/Views/Store/SizeListing.cshtml
@model IEnumerable<MZXRM.PSS.WebClient.Models.Size>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Quantity
        </th>
       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @if (item.Name != "00-00")
        {
            <td>
                <input id="Qty_@item.Id" name="Qty_@item.Id" value="" onchange="adjustQuantity(@item.Id);" />
            </td>}

        else
        {
            <td>
                <input id="Qty_@item.Id" name="Qty_@item.Id" value="" onchange="adjustQuantity(@item.Id);" disabled />
            </td>
        }

    </tr>
}

</table>